CREATE TABLE "trip_ticket_types" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "trip_ticket_types_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"trip_id" integer NOT NULL,
	"name_en" text NOT NULL,
	"name_ru" text NOT NULL,
	"price_in_cents" integer NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);--> statement-breakpoint
ALTER TABLE "trip_ticket_types" ADD CONSTRAINT "trip_ticket_types_trip_id_trips_id_fk" FOREIGN KEY ("trip_id") REFERENCES "public"."trips"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "trip_ticket_types_trip_id_idx" ON "trip_ticket_types" USING btree ("trip_id");--> statement-breakpoint

INSERT INTO "trip_ticket_types" (
	"trip_id",
	"name_en",
	"name_ru",
	"price_in_cents",
	"sort_order",
	"is_active"
)
SELECT
	"id",
	'Adult',
	'Взрослый',
	"adult_trip_price_in_cents",
	0,
	true
FROM "trips"
WHERE "adult_trip_price_in_cents" IS NOT NULL;--> statement-breakpoint

INSERT INTO "trip_ticket_types" (
	"trip_id",
	"name_en",
	"name_ru",
	"price_in_cents",
	"sort_order",
	"is_active"
)
SELECT
	"id",
	'Child',
	'Ребенок',
	"child_trip_price_in_cents",
	1,
	true
FROM "trips"
WHERE trim(coalesce("child_age", '')) <> ''
AND "child_trip_price_in_cents" IS NOT NULL;--> statement-breakpoint

INSERT INTO "trip_ticket_types" (
	"trip_id",
	"name_en",
	"name_ru",
	"price_in_cents",
	"sort_order",
	"is_active"
)
SELECT
	"id",
	'Infant',
	'Младенец',
	0,
	2,
	true
FROM "trips"
WHERE trim(coalesce("infant_age", '')) <> '';
