CREATE TABLE "trip_booking_ticket_types" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "trip_booking_ticket_types_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"booking_id" integer NOT NULL,
	"ticket_type_id" integer,
	"ticket_name_en" text NOT NULL,
	"ticket_name_ru" text NOT NULL,
	"unit_price_in_cents" integer NOT NULL,
	"quantity" integer NOT NULL,
	"total_price_in_cents" integer NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);--> statement-breakpoint
ALTER TABLE "trip_booking_ticket_types" ADD CONSTRAINT "trip_booking_ticket_types_booking_id_trip_bookings_id_fk" FOREIGN KEY ("booking_id") REFERENCES "public"."trip_bookings"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "trip_booking_ticket_types" ADD CONSTRAINT "trip_booking_ticket_types_ticket_type_id_trip_ticket_types_id_fk" FOREIGN KEY ("ticket_type_id") REFERENCES "public"."trip_ticket_types"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "trip_booking_ticket_types_booking_id_idx" ON "trip_booking_ticket_types" USING btree ("booking_id");
