ALTER TABLE "trip_bookings" ADD COLUMN IF NOT EXISTS "visitor_id" text;
ALTER TABLE "trip_bookings" ADD COLUMN IF NOT EXISTS "journey_id" text;
ALTER TABLE "trip_bookings" ADD COLUMN IF NOT EXISTS "first_touch" jsonb;
ALTER TABLE "trip_bookings" ADD COLUMN IF NOT EXISTS "last_touch" jsonb;
ALTER TABLE "trip_bookings" ADD COLUMN IF NOT EXISTS "original_landing_page" text;
ALTER TABLE "trip_bookings" ADD COLUMN IF NOT EXISTS "current_landing_page" text;
ALTER TABLE "trip_bookings" ADD COLUMN IF NOT EXISTS "attribution_referrer" text;
ALTER TABLE "trip_bookings" ADD COLUMN IF NOT EXISTS "utm_adgroup" text;
ALTER TABLE "trip_bookings" ADD COLUMN IF NOT EXISTS "utm_ad" text;
CREATE INDEX IF NOT EXISTS "trip_booking_visitor_id_idx" ON "trip_bookings" ("visitor_id");
CREATE INDEX IF NOT EXISTS "trip_booking_journey_id_idx" ON "trip_bookings" ("journey_id");

CREATE TABLE IF NOT EXISTS "contact_clicks" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "event_id" uuid NOT NULL,
  "channel" text NOT NULL,
  "page_path" text NOT NULL,
  "cta_location" text,
  "trip_id" integer,
  "resort" text,
  "visitor_id" text,
  "journey_id" text,
  "gclid" text,
  "gbraid" text,
  "wbraid" text,
  "yclid" text,
  "utm_source" text,
  "utm_medium" text,
  "utm_campaign" text,
  "utm_content" text,
  "utm_term" text,
  "utm_adgroup" text,
  "utm_ad" text,
  "first_touch" jsonb,
  "last_touch" jsonb,
  "original_landing_page" text,
  "current_landing_page" text,
  "initial_referrer" text,
  "latest_referrer" text,
  "clicked_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
ALTER TABLE "contact_clicks" ADD COLUMN IF NOT EXISTS "event_id" uuid;
ALTER TABLE "contact_clicks" ADD COLUMN IF NOT EXISTS "cta_location" text;
ALTER TABLE "contact_clicks" ADD COLUMN IF NOT EXISTS "visitor_id" text;
ALTER TABLE "contact_clicks" ADD COLUMN IF NOT EXISTS "journey_id" text;
ALTER TABLE "contact_clicks" ADD COLUMN IF NOT EXISTS "first_touch" jsonb;
ALTER TABLE "contact_clicks" ADD COLUMN IF NOT EXISTS "last_touch" jsonb;
ALTER TABLE "contact_clicks" ADD COLUMN IF NOT EXISTS "initial_referrer" text;
ALTER TABLE "contact_clicks" ADD COLUMN IF NOT EXISTS "latest_referrer" text;
CREATE UNIQUE INDEX IF NOT EXISTS "contact_click_event_id_uidx" ON "contact_clicks" ("event_id") WHERE "event_id" IS NOT NULL;
CREATE INDEX IF NOT EXISTS "contact_click_journey_id_idx" ON "contact_clicks" ("journey_id");
CREATE INDEX IF NOT EXISTS "contact_click_visitor_id_idx" ON "contact_clicks" ("visitor_id");
CREATE INDEX IF NOT EXISTS "contact_click_clicked_at_idx" ON "contact_clicks" ("clicked_at");
